spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: ''
    password: ''
  liquibase:
    change-log: classpath:db.changelog-master.yaml
    enabled: true
    default-schema: accounting
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
